const competenceOptions = [
    { value: "java", label: "Java" },
    { value: "python", label: "Python" },
    { value: "javascript", label: "JavaScript" },
    { value: "typescript", label: "TypeScript" },
    { value: "html", label: "HTML" },
    { value: "css", label: "CSS" },
    { value: "react", label: "React" },
    { value: "angular", label: "Angular" },
    { value: "vuejs", label: "Vue.js" },
    { value: "nodejs", label: "Node.js" },
    { value: "expressjs", label: "Express.js" },
    { value: "mongodb", label: "MongoDB" },
    { value: "sql", label: "SQL" },
    { value: "php", label: "PHP" },
    { value: "laravel", label: "Laravel" },
    { value: "ruby", label: "Ruby" },
    { value: "rails", label: "Ruby on Rails" },
    { value: "csharp", label: "C#" },
    { value: "dotnet", label: ".NET" },
    { value: "swift", label: "Swift" },
    { value: "kotlin", label: "Kotlin" },
    { value: "flutter", label: "Flutter" },
    { value: "go", label: "Go" },
    { value: "dart", label: "Dart" },
    { value: "rust", label: "Rust" },
    { value: "shell", label: "Shell Scripting" },
    { value: "spring", label: "Spring Framework" },
    { value: "django", label: "Django" },
    { value: "rubyonrails", label: "Ruby on Rails" },
    { value: "laravel", label: "Laravel" },
    { value: "expressjs", label: "Express.js" },
    { value: "flask", label: "Flask" },
    { value: "aspnet", label: "ASP.NET" },
    { value: "docker", label: "Docker" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "jenkins", label: "Jenkins" },
    { value: "travisci", label: "Travis CI" },
    { value: "gitlabci", label: "GitLab CI/CD" },
    { value: "ansible", label: "Ansible" },
    { value: "terraform", label: "Terraform" },
    { value: "helm", label: "Helm" },
    { value: "prometheus", label: "Prometheus" },
    { value: "git", label: "Git" },
    { value: "github", label: "GitHub" },
    { value: "gitlab", label: "GitLab" },
    { value: "bitbucket", label: "Bitbucket" },
    { value: "junit", label: "JUnit" },
    { value: "selenium", label: "Selenium" },
    { value: "jest", label: "Jest" },
    { value: "pytest", label: "PyTest" },
    { value: "jmockit", label: "JMockit" },
    { value: "owasp", label: "OWASP Top Ten" },
    { value: "ssl", label: "SSL/TLS" },
    { value: "vpn", label: "VPN" },
    { value: "security", label: "Security Compliance" },
    { value: "ethicalhacking", label: "Ethical Hacking" },
    { value: "tcpip", label: "TCP/IP" },
    { value: "httphttps", label: "HTTP/HTTPS" },
    { value: "dns", label: "DNS" },
    { value: "loadbalancing", label: "Load Balancing" },
    { value: "firewalls", label: "Firewalls" },
    { value: "vpns", label: "VPNs" },
    { value: "linux", label: "Linux" },
    { value: "windowsserver", label: "Windows Server" },
    { value: "macos", label: "macOS" },
    { value: "gitlabci", label: "GitLab CI" },
    { value: "jenkins", label: "Jenkins" },
    { value: "travisci", label: "Travis CI" },
    { value: "circleci", label: "CircleCI" },
    { value: "prometheus", label: "Prometheus" },
    { value: "grafana", label: "Grafana" },
    { value: "elkstack", label: "ELK Stack" },
    { value: "splunk", label: "Splunk" },
    { value: "docker", label: "Docker" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "openshift", label: "OpenShift" },
    { value: "tensorflow", label: "TensorFlow" },
    { value: "pytorch", label: "PyTorch" },
    { value: "scikitlearn", label: "scikit-learn" },
    { value: "nlp", label: "Natural Language Processing (NLP)" },
    { value: "computervision", label: "Computer Vision" },
    { value: "ansible", label: "Ansible" },
    { value: "puppet", label: "Puppet" },
    { value: "chef", label: "Chef" },
    { value: "agile", label: "Agile Methodologies" },
    { value: "scrum", label: "Scrum" },
    { value: "kanban", label: "Kanban" },
    { value: "jira", label: "Jira" },
    { value: "trello", label: "Trello" },
    { value: "mysql", label: "MySQL" },
    { value: "postgresql", label: "PostgreSQL" },
    { value: "mongodb", label: "MongoDB" },
    { value: "cassandra", label: "Cassandra" },
    { value: "redis", label: "Redis" },
    { value: "slack", label: "Slack" },
    { value: "microsoftteams", label: "Microsoft Teams" },
    { value: "confluence", label: "Confluence" },
    { value: "sharepoint", label: "SharePoint" },
];


  export default competenceOptions;
